
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/vs/vs2017/Product/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.30+gc0e4b0e683
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 14/2/2026 22:14:36。
      节点 1 上的项目“D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\3.31.10\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      VcpkgTripletSelection:
        Using triplet "x86-windows" from "D:\\myLibs\\vcpkg\\installed\\x86-windows\\"
        Using normalized configuration "Debug"
      ClCompile:
        D:\\vs\\vs2017\\Product\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /I"D:\\myLibs\\vcpkg\\installed\\x86-windows\\include" /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\vs\\vs2017\\Product\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\lib" /LIBPATH:"D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\3.31.10\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      AppLocalFromInstalled:
        pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\myLibs\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\3.31.10\\CompilerIdCXX\\.\\CompilerIdCXX.exe" "D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"
        'pwsh.exe' 不是内部或外部命令，也不是可运行的程序
        或批处理文件。
        命令“pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\myLibs\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\3.31.10\\CompilerIdCXX\\.\\CompilerIdCXX.exe" "D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"”已退出，代码为 9009。
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "D:\\myLibs\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\3.31.10\\CompilerIdCXX\\.\\CompilerIdCXX.exe" "D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\bin" "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.write.1u.tlog" "Debug\\vcpkg.applocal.log"
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\vs\\vs2017\\Product\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\3.31.10\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:05.07
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/vsPro/MultiMediaTool/mediaServer/CMakeFiles/3.31.10/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/vsPro/MultiMediaTool/mediaServer/CMakeFiles/CMakeScratch/TryCompile-zp729e"
      binary: "D:/vsPro/MultiMediaTool/mediaServer/CMakeFiles/CMakeScratch/TryCompile-zp729e"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/vsPro/MultiMediaTool/mediaServer/CMakeFiles/CMakeScratch/TryCompile-zp729e'
        
        Run Build Command(s): D:/vs/vs2017/Product/MSBuild/15.0/Bin/MSBuild.exe cmTC_0bf7e.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.30+gc0e4b0e683
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 14/2/2026 22:14:42。
        节点 1 上的项目“D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\CMakeScratch\\TryCompile-zp729e\\cmTC_0bf7e.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_0bf7e.dir\\Debug\\”。
          正在创建目录“D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\CMakeScratch\\TryCompile-zp729e\\Debug\\”。
          正在创建目录“cmTC_0bf7e.dir\\Debug\\cmTC_0bf7e.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_0bf7e.dir\\Debug\\cmTC_0bf7e.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        VcpkgTripletSelection:
          Using triplet "x86-windows" from "D:\\myLibs\\vcpkg\\installed\\x86-windows\\"
          Using normalized configuration "Debug"
        ClCompile:
          D:\\vs\\vs2017\\Product\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /I"D:\\myLibs\\vcpkg\\installed\\x86-windows\\include" /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_0bf7e.dir\\Debug\\\\" /Fd"cmTC_0bf7e.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "D:\\cmake3.31.10\\share\\cmake-3.31\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27054 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /I"D:\\myLibs\\vcpkg\\installed\\x86-windows\\include" /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_0bf7e.dir\\Debug\\\\" /Fd"cmTC_0bf7e.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "D:\\cmake3.31.10\\share\\cmake-3.31\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
          
        Link:
          D:\\vs\\vs2017\\Product\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\CMakeScratch\\TryCompile-zp729e\\Debug\\cmTC_0bf7e.exe" /INCREMENTAL /NOLOGO /LIBPATH:"D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\lib" /LIBPATH:"D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"D:/vsPro/MultiMediaTool/mediaServer/CMakeFiles/CMakeScratch/TryCompile-zp729e/Debug/cmTC_0bf7e.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/vsPro/MultiMediaTool/mediaServer/CMakeFiles/CMakeScratch/TryCompile-zp729e/Debug/cmTC_0bf7e.lib" /MACHINE:X86  /machine:X86 cmTC_0bf7e.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_0bf7e.vcxproj -> D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\CMakeScratch\\TryCompile-zp729e\\Debug\\cmTC_0bf7e.exe
        AppLocalFromInstalled:
          pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\myLibs\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\CMakeScratch\\TryCompile-zp729e\\Debug\\cmTC_0bf7e.exe" "D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\bin" "cmTC_0bf7e.dir\\Debug\\cmTC_0bf7e.tlog\\cmTC_0bf7e.write.1u.tlog" "cmTC_0bf7e.dir\\Debug\\vcpkg.applocal.log"
          'pwsh.exe' 不是内部或外部命令，也不是可运行的程序
          或批处理文件。
          命令“pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\\myLibs\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\CMakeScratch\\TryCompile-zp729e\\Debug\\cmTC_0bf7e.exe" "D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\bin" "cmTC_0bf7e.dir\\Debug\\cmTC_0bf7e.tlog\\cmTC_0bf7e.write.1u.tlog" "cmTC_0bf7e.dir\\Debug\\vcpkg.applocal.log"”已退出，代码为 9009。
          "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "D:\\myLibs\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\CMakeScratch\\TryCompile-zp729e\\Debug\\cmTC_0bf7e.exe" "D:\\myLibs\\vcpkg\\installed\\x86-windows\\debug\\bin" "cmTC_0bf7e.dir\\Debug\\cmTC_0bf7e.tlog\\cmTC_0bf7e.write.1u.tlog" "cmTC_0bf7e.dir\\Debug\\vcpkg.applocal.log"
        FinalizeBuildStatus:
          正在删除文件“cmTC_0bf7e.dir\\Debug\\cmTC_0bf7e.tlog\\unsuccessfulbuild”。
          正在对“cmTC_0bf7e.dir\\Debug\\cmTC_0bf7e.tlog\\cmTC_0bf7e.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\vsPro\\MultiMediaTool\\mediaServer\\CMakeFiles\\CMakeScratch\\TryCompile-zp729e\\cmTC_0bf7e.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:02.56
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': D:/vs/vs2017/Product/VC/Tools/MSVC/14.16.27023/bin/HostX86/x86/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "D:/cmake3.31.10/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the CXX compiler's linker: "D:/vs/vs2017/Product/VC/Tools/MSVC/14.16.27023/bin/HostX86/x86/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.16.27054.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
